server:
  port: 8761  #指定该服务的端口
eureka:
  client:
    registerWithEureka: false #是否将自己的信息注册到eureka服务器
    fetchRegistry: false   #是否到eureka服务器中抓取注册信息
logging:
  level:
    com.netflix: INFO  #打印的日志的级别
---
server:
  port: 8761
spring:
  application:
    name: fist-server
  profiles: peer1
eureka:
  instance:
    hostname: peer1
  client:
    service-url:
      defaultZone: http://peer2:8762/eureka/
---
  server:
    port: 8762
  spring:
    application:
      name: fist-server
    profiles: peer2
  eureka:
    instance:
      hostname: peer2
    client:
      service-url:
        defaultZone: http://peer1:8761/eureka/
